projectsyn/component-keycloak

- CHANGELOG.md
- class/defaults.yml
- class/keycloak.yml
- docs/modules/ROOT/pages/references/parameters.adoc
* Make the helm chart relase_name overwritable
* Use a version based helm chart directory
> Make helm_values overwritable

- CHANGELOG.md
- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
> Bump the keycloak helm chart version from 9.9.1 to 10.3.0

- .github/workflows/test.yaml
- .gitignore
- Makefile
- Makefile.vars.mk
- tests/test.yml
It's now possible do local compilations without needing a whole catalog
> Add 'make compile' to Make targets

- docs/modules/ROOT/pages/how-tos/change-passwords.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add how-to page to change passwords after installation

- class/defaults.yml
* Enable network policies by default
> Enable network policies by default

- docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
- docs/modules/ROOT/partials/nav.adoc
* Adds an upgrade guide to address the disabling of the network policy for Keycloak.
> Add upgrade guide for 3.x

- docs/modules/ROOT/pages/how-tos/upgrade-3.x-to-4.x.adoc
relevant upgrade instructions from #14 
> Add upgrade instructions from v3 to v4

- .github/workflows/test.yaml
- .sync.yml
- Makefile
- Makefile.custom.mk
- Makefile.vars.mk
- docs/modules/ROOT/pages/explanations/default-features.adoc
- docs/modules/ROOT/pages/how-tos/configure-ingress.adoc
- docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
- docs/modules/ROOT/pages/how-tos/upgrade-3.x-to-4.x.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/pages/tutorials/installation.adoc
* Prepares component for modulesync
> Add Modulesync support

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/explanations/backup.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add k8up support

- Makefile
- tests/builtin.yml
- tests/builtin/secrets_test.go
- tests/external.yml
- tests/external/postgresql_helmchart_not_rendered_test.go
- tests/external/secrets_test.go
> Update tests for latest Commodore version

- component/app.jsonnet
- docs/modules/ROOT/pages/how-tos/openshift-4.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add guide how to install on OCP4

- class/keycloak.yml
- component/main.jsonnet
- component/prometheus-netpol.jsonnet
It is creating a ServiceMonitor, but the label is missing.
> Add synmonitoring label to namespace

- docs/modules/ROOT/pages/how-tos/custom-theme.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add how-to on custom themes

- component/prometheus-netpol.jsonnet
> Only apply prometheus network policy if network policy enabled

- docs/modules/ROOT/pages/how-tos/openshift-4.adoc
> Fix wrong indentation in the docs for OCP how-to

- docs/modules/ROOT/pages/how-tos/custom-theme.adoc
> Add description for default themes in extraEnv

- class/defaults.yml
Leverage YAML anchors to reduce all the duplication in defaults.yaml
> Reduce duplication in defaults

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/how-tos/upgrade-5.x-to-6.x.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/external.yml
> Separate internal and external TLS config

- docs/modules/ROOT/pages/how-tos/openshift-4.adoc
> Use Openshift Service serving cert as recommended default

- docs/modules/ROOT/pages/how-tos/restore.adoc
- docs/modules/ROOT/pages/how-tos/use-built-in-db.adoc
- docs/modules/ROOT/partials/nav.adoc
Adds a tutorial that explains how a Backup and Restore of the built-in database is done with K8up.
Depends on #106 
> Add how-to page to backup and restore Keycloak

- class/defaults.yml
- docs/modules/ROOT/pages/how-tos/use-built-in-db.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
We've deprecated `customer.name` a while ago.
> Fix tenant name reclass references

- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/charts/postgresql/templates/statefulset.yaml
Adjust the golden test for #132.
> Update golden-test for builtin postgres changed to docker.io

- docs/modules/ROOT/pages/how-tos/openshift-4.adoc
- docs/modules/ROOT/pages/how-tos/upgrade-8.x-to-9.x.adoc
Also updated in VSHN commodore defaults.
> Fix indentation of shmVolume params in docs

- docs/modules/ROOT/pages/how-tos/pin-versions.adoc
- docs/modules/ROOT/pages/how-tos/restore.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
> Update the documentation for the name change from keycloak to keycloakx

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labelled as "breaking change" since we recommend a manual backup before doing the upgrade from Keycloak v17 to v18
> Update Keycloak to version 18.0.2

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
> Remove K8up v1 annotations

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
> Upgrade to postgresql to 11.17.0-debian-11-r37

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- [ x Update the documentation.
> Update Keycloak to v19

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
> Upgrade Postgres helm chart to v12.1.3

- docs/modules/ROOT/pages/how-tos/upgrade-10.x-to-11.x.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/partials/nav.adoc
> Upgrade from v10 to v11

- docs/modules/ROOT/pages/how-tos/upgrade-10.x-to-11.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> Fix Upgrade 10.x to 11.x test and navigation link

- tests/openshift-postgres.yml
- tests/openshift-postgres/namespace_test.go
> Add namespace test for OpenShift Postgres

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
See reference: https://syn.tools/syn/explanations/commodore-components/container-images.html
changelog.
> Managing container image versions

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
> Upgrade Keycloak to v20.0.3

- docs/modules/ROOT/pages/how-tos/upgrade-11.x-to-12.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add upgrade how-to from v11 to v12

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
> Upgrade Keycloak to v21

- docs/modules/ROOT/pages/how-tos/upgrade-12.x-to-13.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add upgrade how-to from v12 to v13

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
> Upgrade keycloakx helm Chart to v2.3.0

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
> Bump postgres to 11.22.0-debian-11-r4

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
> Update helm chart to postgresql-12.6.9

- class/defaults.yml
- docs/modules/ROOT/pages/how-tos/openshift-4.adoc
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
- tests/openshift-postgres.yml
With the Helm Chart version 12.7.0 Bitnami introduced a lot more security context configurations by default.
This change also adapts those changes to OpenShift.
changelog.
> Harden the PostgreSQL DB container

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
> Upgrade Keycloak to v22.0.5

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
> Bump Postgres DB from 11.22.0-debian-11-r4 to 15.6.0-debian-12-r5

- class/defaults.yml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
- tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
Reverts projectsyn/component-keycloak#273
> Revert "Bump Postgres DB from 11.22.0-debian-11-r4 to 15.6.0-debian-12-r5"

- docs/modules/ROOT/pages/how-tos/upgrade-13.x-to-14.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add upgrade how-to from v13 to v14

- docs/modules/ROOT/pages/how-tos/upgrade-14.x-to-15.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add upgrade how-to from v14 to v15

- class/defaults.yml
- docs/modules/ROOT/pages/how-tos/upgrade-16.x-to-17.x.adoc
- docs/modules/ROOT/partials/nav.adoc
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
- tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
> Keycloak v24 update

- class/defaults.yml
- class/keycloak.yml
> Make component multi-version aware

- docs/modules/ROOT/pages/how-tos/upgrade-18.x-to-19.x.adoc
- docs/modules/ROOT/partials/nav.adoc
> How to Upgrade from v18 to v19

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/openshift/openshift/openshift/30_k8up.yaml
- tests/openshift.yml
> Support custom CA for Backup Backends
