projectsyn/component-keycloak

CHANGELOG.md, class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
Currently only postgres was supported as an external
database. Adding the vendor variable allow to use
a different supported database as well.
The db variable user has been renamed to username to
make it more clear that it is a string and not an object.
=> Make external db vendor unspecific

CHANGELOG.md, class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
FQDN is more clear that you shouldn't use just the hostname, but
the full qualified domain name used in the ingress or route.
=> Rename keycloak:hostname to keycloak:fqdn

CHANGELOG.md, class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
Latest currently supported configuration.
See #8 for more information about the incompatibility of the Keycloak helm chart 11.0.0.
=> Bump Keycloak helm chart to 10.3.1

docs/modules/ROOT/pages/explanations/default-features.adoc, docs/modules/ROOT/partials/nav.adoc
* Add explanation page to give an overview of the enabled default features
Follows a suggestion from https://github.com/projectsyn/component-keycloak/pull/17#pullrequestreview-665623572
=> Add explanation page to give an overview of the default features

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/explanations/default-features.adoc, docs/modules/ROOT/pages/references/parameters.adoc
* Ensures ingress-controller can connect to Keycloak (provided they are not using host network)
* Adds new parameter `ingress.controllerNamespace`.
* Disable network policy for Keycloak.
* Add a warning in the feature explanation page that users should not blindingly activate netpol for Keycloak when also Ingress.
* Works around a wrong http port in the network policy for Keycloak (upstream PR https://github.com/codecentric/helm-charts/pull/432).
Fixes #19 
Regression from #17 
=> Disable network policy for Keycloak by default

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/explanations/default-features.adoc, docs/modules/ROOT/pages/how-tos/configure-ingress.adoc, docs/modules/ROOT/pages/how-tos/keycloak-tls.adoc, docs/modules/ROOT/pages/how-tos/multi-instance.adoc, docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/pages/tutorials/installation.adoc, docs/modules/ROOT/partials/nav.adoc, tests/external.yml
This increases the security as the cluster internal traffic is encrypted
as well.
The secrets and cert-manager-certificate maintained by ArgoCD are created based whether `termination` and certificate `provider`.
| Combination                                        | Keycloak TLS Secret<br>(keycloak-tls) | Ingress TLS Secret<br>(ingress-tls) | Ingress Certificate (cert-manager) |
|----------------------------------------------------|---------------------------------------|-------------------------------------|------------------------------------|
| Termination: reencrypt,<br>Provider: certmanager   | yes                                   | (generated by cert-manager)         | (via annotation on ingress)        |
| Termination: reencrypt,<br>Provider: vault         | yes …
=> Encrypt cluster-internal traffic

class/defaults.yml, class/keycloak.yml, docs/modules/ROOT/pages/how-tos/custom-theme.adoc, docs/modules/ROOT/pages/how-tos/db-tls.adoc, docs/modules/ROOT/pages/references/parameters.adoc, tests/builtin.yml, tests/builtin/statefulset_keycloak_test.go, tests/external.yml, tests/external/statefulset_keycloak_test.go
Follow-up to #79
This commit adds support for mounting the same volume multiple times, required for the "multiple themes" use case.
Since simply mounting the themes volume to `/opt/jboss/keycloak/themes` would overwrite the default/builtin themes, multiple mounts are required.
=> Document & test multiple themes

class/defaults.yml
This change will ensure that OpenShift routes always use the correct TLS
termination type.
Relates: #80
=> Ensure OpenShift Routes use correct TLS termination

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
The "kubernetes.io/tls-acme" annotation does not do anything anymore and should be removed since it seems to confuse users.
Based off #91 
=> Remove unused ACME annotation

class/defaults.yml
In #96, TLS config for internal and external TLS was segregated, but the
TLS provider got lost.
=> Use correct TLS provider config

class/defaults.yml, class/keycloak.yml, component/prometheus-netpol.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
When compiling the component, a warning would be emmitted:
> using 'release_name' to specify the output name is deprecated. Use
> 'name' instead
This commit addresses this.
=> Update to Helm v3 parameters

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/how-tos/keycloak-tls.adoc, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/openshift/openshift/apps/openshift.yaml, tests/golden/openshift/openshift/openshift/00_namespace.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/configmap-startup.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/ingress.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/prometheusrule.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/service-headless.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/service-http.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/serviceaccount.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/servicemonitor.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/10_admin_secret.yaml, tests/golden/openshift/openshift/openshift/11_db_secret.yaml, tests/openshift.yml
In addition to certmanager- or vault-provided certificates, this commit
adds support to use openshift-provided "service serving certificates".
Based off #89
=> Add support for OpenShift service serving certs

class/defaults.yml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/charts/postgresql/templates/statefulset.yaml
* Switch to annotation on pod instead of on StS
* Add both `k8up.io` and `k8up.syn.tools` annotation to support k8up 2.0
* Add file-extention annotation
* Add `--clean` flag for a conistent restore
=> Fix backup command for builtin PostgreSQL DB

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/builtin.yml, tests/builtin/namespace_test.go, tests/common/boilerplate.go, tests/golden/builtin/builtin/builtin/00_namespace.yaml
=> Allow users to add custom labels to the Keycloak namespace

class/defaults.yml, tests/external.yml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
The helm chart value database hostname was hardcoded to match the
internal builtin mode. This change reenables the external database
hostname is properly passed to the keycloak statefulset.
=> Fix variable database.external.host not passed to the helm chart values

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/builtin/builtin/builtin/11_db_secret.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/11_db_secret.yaml
After the migration to Quarkus, the JBoss directory should not be used
anymore. It might confuse people.
=> Rename database certificate directory to /opt/keycloak/db-certs

docs/modules/ROOT/pages/how-tos/upgrade-8.x-to-9.x.adoc
During the real world upgrade, we have seen that ArgoCD might not prune
the objects ahead, which can cause that the Wildfily keycloak and the
Quarkus keycloak instances run in parallel. This shound't be an issue,
since we migrate to the exact same version, but to be on the safe side
we better turn off the Wilfly instance ahead.
We saw also a conflict generated by the OpenShift router, having two
different named ingress objects with the same hostname. Deleting the
ingress object ahead prevents it.
=> Scale down keycloak and delete the ingress object ahead the upgrade

.cruft.json, docs/modules/ROOT/pages/how-tos/openshift-4.adoc, docs/modules/ROOT/pages/how-tos/upgrade-9.x-to-10.x.adoc, tests/golden/openshift-postgres/openshift-postgres/apps/openshift-postgres.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/00_namespace.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_networkpolicy_infinispan.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/10_admin_secret.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/11_db_secret.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/12_db_certs.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/13_keycloak_certs.yaml, tests/openshift-postgres.yml
Security context parameters have changed in the helm chart.
Adding an additional test, because this test case is not covered.
=> Fix using the built-in DB with OpenShift

class/defaults.yml
The issue regarding network policy has been fixed in keycloak and keycloakx.
Ref: https://github.com/codecentric/helm-charts/pull/432
=> Removing the network policy workaround reference

class/defaults.yml, component/main.jsonnet
Ingress NGINX has changed the labels from app=ingress-nginx to app.kubernetes.io/name=ingress-nginx.
Kubernetes >= 1.21 do set automatically a namespace label kubernetes.io/metadata.name: <namespace>. Therefore manually patching the namespace is no longer required.
=> Update Ingress NGINX network policy configuration for K8s >= 1.21

component/main.jsonnet, tests/builtin.yml, tests/builtin/namespace_test.go, tests/external.yml, tests/golden/builtin/builtin/builtin/00_namespace.yaml, tests/golden/external/external/external/00_namespace.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/00_namespace.yaml, tests/golden/openshift/openshift/openshift/00_namespace.yaml, tests/openshift-postgres.yml, tests/openshift-postgres/namespace_test.go, tests/openshift.yml, tests/openshift/namespace_test.go
SYNMonitoring is no longer relevant and has been removed. Support for component-prometheus and OpenShift 4 has been added.
changelog.
=> Remove SYNMonitoring and add labels for OpenShift and component-prometheus

component/prometheus-netpol.jsonnet, tests/golden/builtin/builtin/builtin/40_netpol.yaml
* Wildfly used the port 9990 for metrics, in Quarkus HTTP 8080 is used
* Rancher Monitoring is no longer in use and therefore being dropped
* component-prometheus is by default deployed in syn-infra-monitoring
* Label app=prometheus has been renamed to app.kubernetes.io/component=prometheus
* The keycloak label is keycloakx since the Quarkus migration
changelog.
=> Fix monitoring network policy to use component-prometheus

component/main.jsonnet
When using `vault` with `reencrypt` the wrong provider parameter is checked in the code. This commit fixes that
changelog.
=> Fix wrong provider parameter for ingress when using vault

component/main.jsonnet
The component creates a tls secret of type `opaque` as the type is not set explicitely. This causes issues with the operator, as the operator expects the secret type to be `kubernetes.io/tls`
changelog.
=> Fix wrong type of tls secret for ingress object when using provider vault

docs/modules/ROOT/pages/how-tos/custom-theme.adoc, docs/modules/ROOT/pages/how-tos/openshift-4.adoc
OpenShift 4.11 introduces pod security admission globally.
changelog.
=> Add Keycloak Pod Security Admission documentation for OpenShift 4

class/defaults.yml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Requries at least Kubernetes v1.23 for HPA
=> Upgrade Keycloakx Helm Chart to v2.2.2

docs/modules/ROOT/pages/how-tos/upgrade-12.x-to-13.x.adoc
Keycloak clustering doesn't work during the upgrade and needs to be disabled during the upgrade.
=> Update the v21 update procedure notes with an Infinispan setup

class/defaults.yml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
https://hub.docker.com/r/bitnami/bitnami-shell
"This container image is deprecated in favor of
https://hub.docker.com/r/bitnami/os-shell"
changelog.
=> Change bitnami-shell to os-shell

docs/modules/ROOT/pages/how-tos/pin-versions.adoc
The component has changed the chart version and image tag parameters in the version v12. This updated the documentation to reflect this.
changelog.
=> Update the Pin versions documentation adapting the parameter change

class/defaults.yml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
As it is default in OpenJDK17 since Keycloak v21.
Ref: https://github.com/keycloak/keycloak/blob/release/21.0/quarkus/container/Dockerfile#L20
changelog.
=> Remove UseContainerSupport from JAVA_OPS 

class/defaults.yml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
=> Remove java.awt.headless

class/defaults.yml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Keycloak v22 ships with [IPv6 enabled](https://github.com/keycloak/keycloak/issues/15003) by default.
changelog.
=> Remove JAVA_OPTS java.net.preferIPv4Stack=true

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml, tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
The default realtiv path of Keycloak has changed from `/auth` to `/` with the https://www.keycloak.org/migration/migrating-to-quarkus[migration to Quarkus]. To preserve the legacy behavior of Wildfly set the relativePath to `/auth`.
changelog.
=> Change relative path from /auth to / by default

docs/modules/ROOT/pages/how-tos/upgrade-14.x-to-15.x.adoc
=> Improvements in the upgrade documentation of v14 to v15
